name: Deploy Supabase Edge Function

on:
  workflow_dispatch: {}
  push:
    paths:
      - "supabase/functions/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Supabase CLI (no Docker, no DB link)
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Supabase version
        run: supabase --version

      # Set function secrets directly against the project (no link)
      - name: Set Edge Function secrets
        run: |
          supabase secrets set \
            SUPABASE_URL="${{ secrets.SUPABASE_URL }}" \
            SUPABASE_SERVICE_ROLE_KEY="${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
            GRAPH_BASE="https://graph.microsoft.com/v1.0" \
            EDGE_FUNCTION_SECRET="${{ secrets.EDGE_FUNCTION_SECRET }}" \
            --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      # Deploy the function directly with --project-ref
      - name: Deploy worker-run
        run: supabase functions deploy worker-run --project-ref "${{ secrets.SUPABASE_PROJECT_REF }}"
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
